# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cov_S_hat_infty1_S_hat_infty2_cpp <- function(J_s, K_s, g_s, h_s, Index_S_hat_infty1_s, Index_S_hat_infty2_s, epsilon_s, m_s, s_squared_s, v_s, n, Number_of_Est_s) {
    .Call('_glrm_Cov_S_hat_infty1_S_hat_infty2_cpp', PACKAGE = 'glrm', J_s, K_s, g_s, h_s, Index_S_hat_infty1_s, Index_S_hat_infty2_s, epsilon_s, m_s, s_squared_s, v_s, n, Number_of_Est_s)
}

CreateM_cpp <- function(J_s, Number_of_Est_s, K_s, g_s, epsilon_s, m_s, s_squared_s, v_s, n) {
    .Call('_glrm_CreateM_cpp', PACKAGE = 'glrm', J_s, Number_of_Est_s, K_s, g_s, epsilon_s, m_s, s_squared_s, v_s, n)
}

CreateQ_cpp <- function(J_s, Number_of_Est_s, K_s, epsilon_s, m_s, s_squared_s, v_s, n) {
    .Call('_glrm_CreateQ_cpp', PACKAGE = 'glrm', J_s, Number_of_Est_s, K_s, epsilon_s, m_s, s_squared_s, v_s, n)
}

CreateR_cpp <- function(J_s, Number_of_Est_s, K_s, epsilon_s, m_s, s_squared_s, v_s, n) {
    .Call('_glrm_CreateR_cpp', PACKAGE = 'glrm', J_s, Number_of_Est_s, K_s, epsilon_s, m_s, s_squared_s, v_s, n)
}

Sim_MSE_bullet_GLR_cpp <- function(S_sim, v_sim, n, NumberOfSimulations, K_s, J_s, Number_of_Est_s, h_s, g_s, v_s, m_s, s_squared_s) {
    .Call('_glrm_Sim_MSE_bullet_GLR_cpp', PACKAGE = 'glrm', S_sim, v_sim, n, NumberOfSimulations, K_s, J_s, Number_of_Est_s, h_s, g_s, v_s, m_s, s_squared_s)
}

Sim_MSE_bullet_LR_cpp <- function(S_sim, v_sim, n, NumberOfSimulations, W_s, v_s, m_s) {
    .Call('_glrm_Sim_MSE_bullet_LR_cpp', PACKAGE = 'glrm', S_sim, v_sim, n, NumberOfSimulations, W_s, v_s, m_s)
}

Sim_MSE_LR_canonical_cpp <- function(S_sim, v_sim, n, NumberOfSimulations, v_s, m_s) {
    .Call('_glrm_Sim_MSE_LR_canonical_cpp', PACKAGE = 'glrm', S_sim, v_sim, n, NumberOfSimulations, v_s, m_s)
}

Sim_MSE_CL_cpp <- function(S_sim, n, NumberOfSimulations, v_s, m_s) {
    .Call('_glrm_Sim_MSE_CL_cpp', PACKAGE = 'glrm', S_sim, n, NumberOfSimulations, v_s, m_s)
}

